name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: install
        env:
          SECRET: ${{ secrets.MY_SECRET }}
          GIT_SSH_COMMAND: ssh -i ~/my_secret
        run: |
          echo "$MY_SECRET" > ~/my_secret
          chmod 600 ~/my_secret
          yarn
      - name: run script
        run: yarn start
